services:
  bark-encrypt:
    build:
      context: ..
      dockerfile: ../Dockerfile
    container_name: bark-encrypt
    volumes:
      - ./config.yaml:/app/config.yaml
    restart: unless-stopped
    env_file:
      - .env